### ISSUE TITLE
Class 'MacsiDigital\Zoom\Zoom' not found

### ISSUE THREAD

**Issue by cyberdrunk2069** [MacsiDigital/zoom-laravel#1]
After installation, publishing config, added keys and then added service provider, the example code gives this error, Class 'MacsiDigital\Zoom\Zoom' not found

`
     <?php

    namespace App\Http\Controllers;

    use Illuminate\Http\Request;
    use MacsiDigital\Zoom\Zoom;

    class ZoomController extends Controller
    {
        public function users () {
            $zoom = new Zoom();

            $users = $zoom->users->list();
            return response($users);
        }
    }
`

**Comment by colinhall17** [comment]
HI,

Apologies in the delay in getting back to you, this is now a deprecated repo.  Try MacsiDigital/laravel-zoom.

It has more Laravel like syntax and is the one that is activly maintained.
